# Generated by Django 3.2.5 on 2021-07-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='recommend_menu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
